### ISSUE TITLE
Results not being produced for some samples

### ISSUE THREAD

**Issue by ammaraziz** [grubaughlab/DENV-genomics#1]
Hi there,

Thank you for both the DengueSeq protocol and this pipeline. We've (VIDRL-Australia) used both for sequencing Dengue 2 and it's working wonderfully. 

We ran 20 samples through the pipeline, a few did not generate any consensus due to lack of reads (samples had high Ct values), with the rest generating a consensus apart from two samples. These two samples had plenty of reads, great depth, were included in the summary files (eg `top_virus_all_samples.tsv`) but they do not appear anywhere in the alignments/consensus/bam folders.

I thought I was going a tad crazy, so I reran just the two samples giving me trouble and yep, the data is generated by never moved into the results folder.  I ran the pipeline again with the `--temp` flag, everything is there.

Any assistance would be appreciated. I can send the pipeline output via a link (can't share in the open unfortunately).

Thanks,

Ammar

**Comment by ammaraziz** [comment]
Wrong repo! sorry

**Comment by grubaughlab** [comment]
Hi Ammar,

Glad that the pipeline is working for you! I'm adding Verity and Chantal to
see if they can help, but I'm not exactly sure of the issue.

Best,

Nate
